#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements.
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts
#sed -i 's/157.240.6.35/8.8.8.8/' ~/hosts.new
#echo "some text" >> ~/hosts.new
